### ISSUE TITLE
Peer to peer code review.

### ISSUE THREAD

**Issue by ameerhamzakhalid** [gauravgangwarweb/To-Do-List#6]
Hi @gauravgangwarweb 

Good job!
Your project is complete! There is nothing else to say
(Highlights) Good Points: 💪

    Good commit messages. ✔️
    No linter errors. ✔️
    Followed Github flow ✔️
    Professional README file. ✔️
    All features are working properly ✔️

**Comment by gitbygaurav** [comment]
> Hi @gauravgangwarweb
> 
> Good job! Your project is complete! There is nothing else to say (Highlights) Good Points: 💪
> 
> ```
> Good commit messages. ✔️
> No linter errors. ✔️
> Followed Github flow ✔️
> Professional README file. ✔️
> All features are working properly ✔️
> ```

Hi @ameerhamzakhalid 

Thanks for your review 😊.
